# -*- coding: utf-8 -*-
"""python-practice

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kAWQZzq4fUnC4GyHwfT3Bmq3uIynwQ8T
"""

years_list = [1991,1992,1993,1994,1995]

print(years_list)

print(years_list[3])

print(years_list[-1])

things =  ["mozzarella", "cinderella", "salmonella"]

print(things)

things[1] = things[1].capitalize()
things

things[0] = things[0].upper()
things

things.pop()
things

surprise = ['Groucho', 'Chico', 'Harpo']

surprise[-1] = surprise[-1].lower()
print(surprise)
surprise = surprise[::-1]
print(surprise)
surprise[0] = surprise[0].title()
print(surprise)

e2f = {'dog':'chien', 'cat':'chat', 'walrus':'morse'}
print(e2f)

print(e2f['walrus'])

f2e = {}
for key, value in e2f.items():
  f2e[value] = key
print(f2e)

f2e['chien']

print(set(e2f))

life = {'animals':{'cats':['Henri', 'Grumpy', 'Lucy'], 'octopi':{}, 'emus':{}}, 'plants':{}, 'other':{}}
print(life)

print(life.keys())

print(life['animals'].keys())

print(life['animals']['cats'])